// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_yrSnhPhf6FhFjq5_b4Hs3sFcMN73RY4',
    appId: '1:411854215980:web:6ddfe515ead45750216a89',
    messagingSenderId: '411854215980',
    projectId: 'fir-lab-7092f',
    authDomain: 'fir-lab-7092f.firebaseapp.com',
    storageBucket: 'fir-lab-7092f.appspot.com',
    measurementId: 'G-JVYD6MW13J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC62R57iIQVAVaPbqhzOe_zJqv1WtwFvh0',
    appId: '1:411854215980:android:c33a432b9a2d4454216a89',
    messagingSenderId: '411854215980',
    projectId: 'fir-lab-7092f',
    storageBucket: 'fir-lab-7092f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1nuNLqi2o4-No-B6OKcuY2DoLeMMBTCU',
    appId: '1:411854215980:ios:2c9238d69e82ea96216a89',
    messagingSenderId: '411854215980',
    projectId: 'fir-lab-7092f',
    storageBucket: 'fir-lab-7092f.appspot.com',
    iosBundleId: 'com.example.firebaseLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1nuNLqi2o4-No-B6OKcuY2DoLeMMBTCU',
    appId: '1:411854215980:ios:2ed611b4745873b5216a89',
    messagingSenderId: '411854215980',
    projectId: 'fir-lab-7092f',
    storageBucket: 'fir-lab-7092f.appspot.com',
    iosBundleId: 'com.example.firebaseLab.RunnerTests',
  );
}
